### ISSUE TITLE
Errors : returning internal errors to the client 

### ISSUE THREAD

**Issue by MedGhassen** [restorecommerce/chassis-srv#1]
Hi , I'm throwing  an error of predefined type that causes an internal error and also return to the client an internal error  : result 0 error:"Internal: internal" 
Here is what I'm doing to throw the error : 
`
let errors = require('restore-chassis-srv').errors;
`
`throw new errors.NotFound('Item Not Found');`

**Comment by marshauf** [comment]
I can not reproduce this error. What is the content of error.details?
